"""Configuration and local environment-file helpers.

The dashboard is deliberately self-hosted, so a small ``.env`` file is the most
practical place for its local secrets.  This module keeps that file anchored to
the project root (rather than the process working directory), writes it with
owner-only permissions, and lets real process environment variables take
precedence over it.
"""

from __future__ import annotations

import json
import os
import secrets
import tempfile
from datetime import timedelta
from pathlib import Path
from typing import Mapping

from dotenv import dotenv_values, load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_ENV_FILE = PROJECT_ROOT / ".env"
KNOWN_INSECURE_SECRET = "default-secret-key-for-initial-setup"


def environment_file(value: str | Path | None = None) -> Path:
    """Resolve the local secret file, optionally from ``URIO_ENV_FILE``.

    Keeping this configurable lets a container mount a durable private volume
    without having to make the application source directory writable.
    """
    configured = value if value is not None else os.getenv("URIO_ENV_FILE")
    return Path(configured).expanduser() if configured else DEFAULT_ENV_FILE


def env_bool(value: object | None, default: bool = False) -> bool:
    """Parse common environment boolean values without surprising fallbacks."""
    if value is None:
        return default
    return str(value).strip().lower() in {"1", "true", "t", "yes", "y", "on"}


def env_int(value: object | None, default: int, *, minimum: int | None = None, maximum: int | None = None) -> int:
    """Parse a bounded integer environment setting."""
    try:
        result = int(str(value))
    except (TypeError, ValueError):
        result = default
    if minimum is not None:
        result = max(minimum, result)
    if maximum is not None:
        result = min(maximum, result)
    return result


def load_environment(env_file: str | Path | None = None) -> None:
    """Load local configuration once, while allowing deployment env vars to win."""
    path = environment_file(env_file)
    if path.exists():
        load_dotenv(path, override=False)


def _quote_env_value(value: object) -> str:
    """Return a dotenv-safe quoted scalar.

    JSON double-quoted strings are valid dotenv values and correctly preserve
    password hashes, Fernet keys, spaces and dollar signs.
    """
    return json.dumps(str(value), ensure_ascii=False)


def persist_environment(
    updates: Mapping[str, object],
    *,
    remove: tuple[str, ...] = (),
    env_file: str | Path | None = None,
) -> None:
    """Atomically persist local values and update the current process environment.

    This is intentionally used only for the dashboard's setup/migration flow.
    Deployment systems can still provide values directly through their process
    environment; those values are never printed or logged.
    """
    path = environment_file(env_file)
    existing = {
        key: value
        for key, value in dotenv_values(path).items()
        if value is not None
    }
    for key in remove:
        existing.pop(key, None)
    for key, value in updates.items():
        existing[key] = str(value)

    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary_name = tempfile.mkstemp(prefix=".env.", dir=path.parent, text=True)
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as env_file:
            env_file.write("# Generated by URnetwork Stats Dashboard. Keep this file private.\n")
            for key in sorted(existing):
                env_file.write(f"{key}={_quote_env_value(existing[key])}\n")
            env_file.flush()
            os.fsync(env_file.fileno())
        os.chmod(temporary_path, 0o600)
        os.replace(temporary_path, path)
        os.chmod(path, 0o600)
    except Exception:
        temporary_path.unlink(missing_ok=True)
        raise

    for key in remove:
        os.environ.pop(key, None)
    for key, value in updates.items():
        os.environ[key] = str(value)


def default_app_config() -> dict[str, object]:
    """Build Flask configuration at application-factory time.

    A fresh random in-memory key is deliberately used before installation.  A
    public, fixed fallback would allow forged Flask sessions during setup.
    """
    app_env = os.getenv("APP_ENV", "development").strip().lower()
    persisted_secret = os.getenv("SECRET_KEY")
    if persisted_secret == KNOWN_INSECURE_SECRET:
        persisted_secret = None

    instance_dir = Path(os.getenv("INSTANCE_DIR", str(PROJECT_ROOT / "instance"))).expanduser()
    database_url = os.getenv(
        "DATABASE_URL",
        f"sqlite:///{instance_dir / 'transfer_stats.db'}",
    )
    # Credentialed CORS must use explicit origins. Silently ignore a wildcard
    # rather than turning an operator typo into a cross-site session exposure.
    allowed_origins = tuple(
        origin.strip()
        for origin in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")
        if origin.strip() and origin.strip() != "*"
    )

    return {
        "APP_ENV": app_env,
        "BASE_DIR": str(PROJECT_ROOT),
        "INSTANCE_DIR": str(instance_dir),
        "ENV_FILE": str(environment_file()),
        "SQLALCHEMY_DATABASE_URI": database_url,
        "SQLALCHEMY_TRACK_MODIFICATIONS": False,
        "SECRET_KEY": persisted_secret or secrets.token_urlsafe(48),
        "SECRET_KEY_PERSISTED": bool(persisted_secret),
        "ADMIN_PASSWORD_HASH": os.getenv("ADMIN_PASSWORD_HASH", ""),
        # Only used once to migrate installations made by older releases.
        "LEGACY_ADMIN_PASSWORD": os.getenv("ADMIN_PASSWORD", ""),
        "CREDENTIAL_ENCRYPTION_KEY": os.getenv("CREDENTIAL_ENCRYPTION_KEY", ""),
        "CORS_ALLOWED_ORIGINS": allowed_origins,
        "SESSION_COOKIE_NAME": "urio_session",
        "SESSION_COOKIE_HTTPONLY": True,
        "SESSION_COOKIE_SAMESITE": os.getenv("SESSION_COOKIE_SAMESITE", "Lax"),
        # Local HTTP development remains possible; production must opt into HTTPS.
        "SESSION_COOKIE_SECURE": env_bool(
            os.getenv("SESSION_COOKIE_SECURE"), default=app_env == "production"
        ),
        "PERMANENT_SESSION_LIFETIME": timedelta(
            hours=env_int(os.getenv("SESSION_LIFETIME_HOURS"), 12, minimum=1, maximum=168)
        ),
        "MAX_CONTENT_LENGTH": env_int(
            os.getenv("MAX_REQUEST_BYTES"), 64 * 1024, minimum=1024, maximum=1024 * 1024
        ),
        "LOGIN_MAX_ATTEMPTS": env_int(
            os.getenv("LOGIN_MAX_ATTEMPTS"), 5, minimum=1, maximum=20
        ),
        "LOGIN_WINDOW_SECONDS": env_int(
            os.getenv("LOGIN_WINDOW_SECONDS"), 15 * 60, minimum=60, maximum=24 * 60 * 60
        ),
        "MIN_ADMIN_PASSWORD_LENGTH": env_int(
            os.getenv("MIN_ADMIN_PASSWORD_LENGTH"), 12, minimum=8, maximum=128
        ),
        "SCHEDULER_ENABLED": env_bool(os.getenv("RUN_SCHEDULER"), default=True),
        "AUTO_REMOVE_OFFLINE_DEVICES": env_bool(
            os.getenv("AUTO_REMOVE_OFFLINE_DEVICES"), default=False
        ),
        "STATS_RETENTION_DAYS": env_int(
            os.getenv("STATS_RETENTION_DAYS"), 90, minimum=7, maximum=3650
        ),
        "PROVIDER_STATS_RETENTION_DAYS": env_int(
            os.getenv("PROVIDER_STATS_RETENTION_DAYS"), 90, minimum=7, maximum=3650
        ),
        "WEBHOOK_ALLOWED_HOSTS": tuple(
            host.strip().lower()
            for host in os.getenv(
                "WEBHOOK_ALLOWED_HOSTS",
                "discord.com,discordapp.com,canary.discord.com,ptb.discord.com",
            ).split(",")
            if host.strip()
        ),
        "PUBLIC_DASHBOARD_DEFAULT": env_bool(
            os.getenv("PUBLIC_DASHBOARD_ENABLED"), default=False
        ),
        "PUBLIC_DASHBOARD_FINANCIALS_DEFAULT": env_bool(
            os.getenv("PUBLIC_DASHBOARD_SHOW_FINANCIALS"), default=False
        ),
        "TRUST_PROXY_HEADERS": env_bool(os.getenv("TRUST_PROXY_HEADERS"), default=False),
        "ENABLE_HSTS": env_bool(os.getenv("ENABLE_HSTS"), default=app_env == "production"),
    }
